#!/bin/bash
# WARNING: this script will destroy data on the selected disk.
# This script can be run by executing the following:
#   curl -sL https://git.io/Jfpvf | bash
set -uo pipefail
trap 's=$?; printf "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Install KDE, Firefox and Bluetooth
sudo pacman -S archlinux-keyring
yay -S cifs-utils gparted plasma-nm sddm sddm-kcm firefox firefox-i18n-de plasma kde-applications gst-libav gst-plugins-good gst-plugins-ugly gst-plugins-bad pulseaudio-alsa pulseaudio-bluetooth bluez-utils bluez texlive-most biber texstudio sane libreoffice-fresh hunspell hunspell-de sane skanlite vlc plasma5-applets-kde-arch-update-notifier-git nohang-git

# Enable the services
sudo systemctl enable NetworkManager
sudo systemctl enable bluetooth
sudo systemctl enable sddm
sudo systemctl start sddm
sudo systemctl enable --now nohang-desktop.service
