#!/bin/bash
# This script can be run by executing the following:
#   curl -sL https://git.io/JfLYQ | bash
# and should be run as user

set -uo pipefail
trap 's=$?; printf "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

block=$(dialog --stdout --inputbox "Wo soll Arch installiert werden (ohne Pfad)?" 0 0) || exit 1
clear
: ${block:?"You have to answer!"}

modell=$(dialog --stdout --inputbox "Welches Raspberry Pi Modell (nur Nummer)?" 0 0) || exit 1
clear
: ${modell:?"You have to answer!"}

version=$(dialog --stdout --inputbox "Soll Raspberry Pi latest (anworte: normal) oder Aarch64 (antworte: aarch64) installiert werden)?" 0 0) || exit 1
clear
: ${version:?"You have to answer!"}

if [ $modell = "zero" ];
then 
    wlan=$(dialog --stdout --inputbox "Soll WLAN eingerichtet werden?" 0 0) || exit 1
    clear
    : ${wlan:?"You have to answer with yes or no."}
fi

if [ $wlan = "yes" ] || [ $wlan = "ja" ];
then 
    ssid=$(dialog --stdout --inputbox "Wie lautet die SSID?" 0 0) || exit 1
    clear
    : ${ssid:?"You have to answer with yes or no."}
    passwort=$(dialog --stdout --inputbox "Wie lautet das Passwort?" 0 0) || exit 1
    clear
    : ${passwort:?"You have to answer with yes or no."}
fi

echo "test"
echo $wlan
